import os
import sys
import argparse

sys.path.append('..')
sys.path.append('img_sim')
sys.path.append('word_sim')
from img_predict import img_sim
from word_predict import word_sim
#from img_sim.img_predict import img_sim
#from word_sim.word_predict import word_sim

class img_word_sim(object):
    __slots__ = ['img_model',
                 'word_model'
            ]
    
    def __init__(self, cnn_model_type='ResNet', lang='jp', word_dict='jp_wiki', feature=False, gpu_id=-1):
        self.img_model = img_sim(model=cnn_model_type,
                                lang=lang,
                                feature=feature,
                                gpu_id=gpu_id
                            )
        
        self.word_model = word_sim(word_dict=word_dict)

    def get_img_sim_norms(self, img, num=5, cutoff=0, sim_type='high'):
        return self.img_model.get_norms(img, num, cutoff, sim_type)

    def get_word_sim_norms(self, subject, img_sim_words, num=5, sim_type='low'):

        img_sim_norms = []
        for img_sim_word in img_sim_words:
            norm = img_sim_word['norm']
            img_sim_norms.append(norm)
        
        return self.word_model.get_norms(subject, img_sim_norms, num, sim_type)
        
    def get_img_word_sim_norms(self, img, subject, multiple=5, num=5, cutoff=0, img_sim='high', word_sim='low'):
        # output size is num. to garantee output size, sufficient number of img_sim_words outputs is neccesary. so firstly it produces max number of classes in img_model.get_norms method, 
        img_sim_words = self.get_img_sim_norms(img, num*multiple, cutoff, img_sim)
        word_sim_words = self.get_word_sim_norms(subject, img_sim_words, num, word_sim)

        img_word_sim_words = self.__calc_score(img_sim_words, word_sim_words)

        result_norms = {'img_word_sim_words': img_word_sim_words,'img_sim_words': img_sim_words, 'word_sim_words': word_sim_words}

        return result_norms

    def __calc_score(self, img_sim_words, word_sim_words):
        sim_words = []
        

        #print(img_sim_words)
        #print(word_sim_words)
        for word_sim_word in word_sim_words:
            
            i_sim = [img_sim_word['sim'] for img_sim_word in img_sim_words if img_sim_word['norm'] == word_sim_word['norm']]
            score = i_sim[0] * (1 - word_sim_word['sim'])

            sim_words.append( {'score': score, 'norm': word_sim_word['norm']} )

        sim_words = sorted(sim_words, key=lambda x: x['score'], reverse=True)

        return sim_words

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--img', '-i', type=str, default=os.path.join('..', '..', 'sample_imgs', 'test.jpg'),
                        help="image you want to predict")
    parser.add_argument('--cnn_model_type', '-cmt', type=str, default='ResNet', choices=['ResNet', 'VGG16', 'AlexNet'],
                        help="CNN model type")
    parser.add_argument('--lang', '-l', type=str, default='jp',
                        help="language to output class")
    parser.add_argument('--word_dict', '-d', type=str, default='jp_wiki_ipadic', choices=['jp_wiki_ipadic', 'jp_wiki_neolog'],
                        help="type of dictionary for word2vec")
    parser.add_argument('--subject', '-s', type=str, default='男性',
                        help="subject to compare with proper norms")
    parser.add_argument('--norms', '-nr', type=str, default=[['イヌ', '犬', 'ドッグ', '飼い犬'], ['カカシ', 'かかし'], ['サボテン', 'カクタス'], ['カンガルー']],
                        help="proper norms to compare with subject")
    parser.add_argument('--img_multiply', '-mt', type=int, default=5,
                        help="num * img_multiply by num classes are generated by img_sim")
    parser.add_argument('--num', '-n', type=int, default=5,
                        help="the number of output")
    parser.add_argument('--img_cutoff', '-ic', type=int, default=1,
                        help="the number of cutoff for top n sim image")
    parser.add_argument('--img_sim', '-is', type=str, default="high", choices=['high', 'low', 'rand', 'mid'],
                        help="output img sim type")
    parser.add_argument('--word_sim', '-ws', type=str, default="low", choices=['high', 'low', 'rand', 'mid'],
                        help="output word sim type")
    parser.add_argument('--feature', '-f', action='store_true',
                        help="use features to output class")
    parser.add_argument('--gpu', '-g', type=int, default=-1,
                        help="GPU ID(put -1 if you don't use gpu)")
    args = parser.parse_args()

    img_word_model = img_word_sim(cnn_model_type=args.cnn_model_type,
                                lang=args.lang,
                                word_dict=args.word_dict,
                                feature=args.feature,
                                gpu_id=args.gpu
                            )
    
    """
    img_sim_words = img_word_model.get_img_sim_norms(img=args.img,
                                                       num=args.num,
                                                       cutoff=args.img_cutoff,
                                                       sim_type=args.img_sim
                                                    )

    print('img sim result\n')
    print('sim: ', args.img_sim)
    print('sim\t\tnorm')

    for img_sim_word in img_sim_words:
        print(round(img_sim_word['sim'], 5), '\t', img_sim_word['norm'])

    word_sim_words = img_word_model.get_word_sim_norms(subject=args.subject,
                                                            img_sim_words=img_sim_words,
                                                            num=args.num,
                                                            sim_type=args.word_sim
                                                            )
    print('')
    print('word sim result\n')
    print('sim: ', args.word_sim)
    print('sim\t\tnorm')
    for word_sim_word in word_sim_words:
        print(round(word_sim_word['sim'], 5), '\t', word_sim_word['norm'])
    
    """

    result_norms = img_word_model.get_img_word_sim_norms(img=args.img,
                                                        subject=args.subject,
                                                        multiple=args.img_multiply,
                                                        num=args.num,
                                                        cutoff=args.img_cutoff,
                                                        img_sim=args.img_sim,
                                                        word_sim=args.word_sim
                                                    )

    print('')
    print('img word sim result\n')
    print('compare with ', args.subject)
    print('img_sim: ', args.img_sim)
    print('word_sim: ', args.word_sim)
    print('sim\t\tnorm')

    for img_word_sim_word in result_norms['img_word_sim_words']:
        print(round(img_word_sim_word['score'], 5), '\t', img_word_sim_word['norm'])
